require "user.keymaps"
require "user.plugins"
require "user.treesitter"
require "user.nvimtree"
require "user.options"
require "user.telescope"
require "user.lsp"
require "user.bufferline"
require "user.color"
require "user.alpha"
require "user.comments"
require "user.autopairs"
require "user.terminal"

vim.g.indentLine_enabled = 1 
vim.g.indent_blankline_char = "│"
vim.g.indent_blankline_char = "▏"
